name: Build Windows App

on:
  workflow_dispatch:  # Allows you to trigger the build manually from the GitHub website
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run Windows Build Script
      run: scripts\build_app.bat
      shell: cmd

    - name: Upload Windows App Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PythonLure-Windows
        path: dist/
